//
//  AxcCIFilterCategory+Type.swift
//  Pods
//
//  Created by 赵新 on 2023/7/31.
//

import CoreImage

public extension AxcCIFilterCategory {
    /// 高动态范围
    enum HighDynamicRange: String {
        /// 手风琴折叠过渡效果
        case accordionFoldTransition
        /// 加法合成
        case additionCompositing
        /// 仿射夹紧变换
        case affineClamp
        /// 仿射平铺变换
        case affineTile
        /// 仿射变换
        case affineTransform
        /// 区域平均
        case areaAverage
        /// 区域对数直方图
        case areaLogarithmicHistogram
        /// 区域最大值
        case areaMaximum
        /// 区域最大Alpha
        case areaMaximumAlpha
        /// 区域最小值
        case areaMinimum
        /// 区域最小Alpha
        case areaMinimumAlpha
        /// 区域最小最大值
        case areaMinMax
        /// 区域最小最大红色
        case areaMinMaxRed
        /// 条形刷过渡效果
        case barsSwipeTransition
        /// 双立方缩放变换
        case bicubicScaleTransform
        /// 使用Alpha遮罩混合
        case blendWithAlphaMask
        /// 使用蓝色遮罩混合
        case blendWithBlueMask
        /// 使用遮罩混合
        case blendWithMask
        /// 使用红色遮罩混合
        case blendWithRedMask
        /// 泛光效果
        case bloom
        /// 光斑模糊
        case bokehBlur
        /// 方框模糊
        case boxBlur
        /// 凹凸失真
        case bumpDistortion
        /// 线性凹凸失真
        case bumpDistortionLinear
        /// 相机校准镜头校正
        case cameraCalibrationLensCorrection
        /// 棋盘格生成器
        case checkerboardGenerator
        /// 圆形溅射失真
        case circleSplashDistortion
        /// 圆形包裹
        case circularWrap
        /// 夹紧
        case clamp
        /// 颜色绝对差异
        case colorAbsoluteDifference
        /// 颜色控制
        case colorControls
        /// 颜色交叉多项式
        case colorCrossPolynomial
        /// 颜色立方体
        case colorCube
        /// 使用遮罩混合的颜色立方体
        case colorCubesMixedWithMask
        /// 带颜色空间的颜色立方体
        case colorCubeWithColorSpace
        /// 颜色反转
        case colorInvert
        /// 颜色矩阵
        case colorMatrix
        /// 单色颜色
        case colorMonochrome
        /// 颜色多项式
        case colorPolynomial
        /// 颜色色阶
        case colorPosterize
        /// 列平均
        case columnAverage
        /// 常量颜色生成器
        case constantColorGenerator
        /// 将 Lab 转换为 RGB
        case convertLabToRGB
        /// 将 RGB 转换为 Lab
        case convertRGBtoLab
        /// 3x3 卷积
        case convolution3X3
        /// 5x5 卷积
        case convolution5X5
        /// 7x7 卷积
        case convolution7X7
        /// 水平 9x9 卷积
        case convolution9Horizontal
        /// 垂直 9x9 卷积
        case convolution9Vertical
        /// 3x3 RGB 卷积
        case convolutionRGB3X3
        /// 5x5 RGB 卷积
        case convolutionRGB5X5
        /// 7x7 RGB 卷积
        case convolutionRGB7X7
        /// 水平 9x9 RGB 卷积
        case convolutionRGB9Horizontal
        /// 垂直 9x9 RGB 卷积
        case convolutionRGB9Vertical
        /// 复印机过渡效果
        case copyMachineTransition
        /// 裁剪
        case crop
        /// 结晶化效果
        case crystallize
        /// 深度模糊效果
        case depthBlurEffect
        /// 圆形模糊
        case discBlur
        /// 使用遮罩解体过渡效果
        case disintegrateWithMaskTransition
        /// 位移失真
        case displacementDistortion
        /// 溶解过渡效果
        case dissolveTransition
        /// 抖动效果
        case dither
        /// 德罗斯特效果
        case droste
        /// 保边提升滤镜
        case edgePreserveUpsampleFilter
        /// 边缘
        case edges
        /// 八折反射平铺
        case eightfoldReflectedTile
        /// 曝光调节
        case exposureAdjust
        /// 伪彩色效果
        case falseColor
        /// 闪光过渡效果
        case flashTransition
        /// 四折反射平铺
        case fourfoldReflectedTile
        /// 四折旋转平铺
        case fourfoldRotatedTile
        /// 四折平移平铺
        case fourfoldTranslatedTile
        /// Gabor 梯度
        case gaborGradients
        /// gamma 调节
        case gammaAdjust
        /// 高斯模糊
        case gaussianBlur
        /// 高斯梯度
        case gaussianGradient
        /// 玻璃畸变
        case glassDistortion
        /// 玻璃菱形
        case glassLozenge
        /// 滑动反射平铺
        case glideReflectedTile
        /// 阴暗效果
        case gloom
        /// 引导滤波
        case guidedFilter
        /// 六边形像素化
        case hexagonalPixellate
        /// 高光阴影调节
        case highlightShadowAdjust
        /// 孔洞失真
        case holeDistortion
        /// 色调调节
        case hueAdjust
        /// 万花筒效果
        case kaleidoscope
        /// 综合校正
        case keystoneCorrectionCombined
        /// 水平校正
        case keystoneCorrectionHorizontal
        /// 垂直校正
        case keystoneCorrectionVertical
        /// K-means
        case kMeans
        /// Lanczos 缩放变换
        case lanczosScaleTransform
        /// 透镜光晕生成器
        case lenticularHaloGenerator
        /// 光线隧道
        case lightTunnel
        /// 线性渐变
        case linearGradient
        /// 线性到SRGB色调曲线
        case linearToSRGBToneCurve
        /// 带掩码的可变模糊
        case maskedVariableBlur
        /// 最大分量
        case maximumComponent
        /// 最大合成
        case maximumCompositing
        /// 中值滤波
        case medianFilter
        /// 网格生成器
        case meshGenerator
        /// 最小分量
        case minimumComponent
        /// 最小合成
        case minimumCompositing
        /// 混合
        case mix
        /// 模块过渡
        case modTransition
        /// 形态梯度
        case morphologyGradient
        /// 形态最大值
        case morphologyMaximum
        /// 形态最小值
        case morphologyMinimum
        /// 矩形形态最大值
        case morphologyRectangleMaximum
        /// 矩形形态最小值
        case morphologyRectangleMinimum
        /// 运动模糊
        case motionBlur
        /// 乘法合成
        case multiplyCompositing
        /// 九切片拉伸
        case ninePartStretched
        /// 九切片平铺
        case ninePartTiled
        /// 噪声降低
        case noiseReduction
        /// op平铺
        case opTile
        /// 翻页过渡
        case pageCurlTransition
        /// 带阴影的翻页过渡
        case pageCurlWithShadowTransition
        /// 平行四边形平铺
        case parallelogramTile
        /// 透视校正
        case perspectiveCorrection
        /// 透视旋转
        case perspectiveRotate
        /// 透视平铺
        case perspectiveTile
        /// 透视变换
        case perspectiveTransform
        /// 带范围的透视变换
        case perspectiveTransformWithExtent
        /// 捏合畸变
        case pinchDistortion
        /// 像素化
        case pixellate
        /// 点阵化
        case pointillize
        /// 径向渐变
        case radialGradient
        /// 波纹过渡
        case rippleTransition
        /// 圆角矩形生成器
        case roundedRectangleGenerator
        /// 行平均值
        case rowAverage
        /// 最近采样
        case sampleNearest
        /// 深褐色调
        case sepiaTone
        /// 阴影材质
        case shadedMaterial
        /// 锐化亮度
        case sharpenLuminance
        /// 六重反射瓦片
        case sixfoldReflectedTile
        /// 六重旋转瓦片
        case sixfoldRotatedTile
        /// 平滑线性渐变
        case smoothLinearGradient
        /// 源位于上方合成
        case sourceAtopCompositing
        /// 源位于内部合成
        case sourceInCompositing
        /// 源位于外部合成
        case sourceOutCompositing
        /// 源位于上方合成
        case sourceOverCompositing
        /// 点色
        case spotColor
        /// 聚光灯
        case spotLight
        /// SRGB色调曲线到线性
        case sRGBToneCurveToLinear
        /// 星光发生器
        case starShineGenerator
        /// 校直滤镜
        case straightenFilter
        /// 拉伸裁剪
        case stretchCrop
        /// 条纹生成器
        case stripesGenerator
        /// 阳光束生成器
        case sunbeamsGenerator
        /// 滑动过渡
        case swipeTransition
        /// 温度和色调
        case temperatureAndTint
        /// 圆环镜头畸变
        case torusLensDistortion
        /// 三角形万花筒
        case triangleKaleidoscope
        /// 三角形瓦片
        case triangleTile
        /// 十二重反射瓦片
        case twelvefoldReflectedTile
        /// 旋转畸变
        case twirlDistortion
        /// 非锐化蒙版
        case unsharpMask
        /// 暗角
        case vignette
        /// 暗角效果
        case vignetteEffect
        /// 漩涡畸变
        case vortexDistortion
        /// 白点调整
        case whitePointAdjust
        /// 缩放模糊
        case zoomBlur
    }
}
