//
//  AxcCIFilterCategory+Type.swift
//  Pods
//
//  Created by 赵新 on 2023/7/31.
//

import CoreImage

// MARK: - [AxcCIFilterCategory.BuiltIn]

public extension AxcCIFilterCategory {
    /// 内置
    enum BuiltIn: String {
        /// 手风琴折叠过渡
        case accordionFoldTransition
        /// 加法合成
        case additionCompositing
        /// 仿射夹紧
        case affineClamp
        /// 仿射平铺
        case affineTile
        /// 仿射变换
        case affineTransform
        /// 区域平均
        case areaAverage
        /// 区域直方图
        case areaHistogram
        /// 区域对数直方图
        case areaLogarithmicHistogram
        /// 区域最大值
        case areaMaximum
        /// 区域最大值Alpha通道
        case areaMaximumAlpha
        /// 区域最小值
        case areaMinimum
        /// 区域最小值Alpha通道
        case areaMinimumAlpha
        /// 区域最小值和最大值
        case areaMinMax
        /// 区域最小值和最大值的红色通道
        case areaMinMaxRed
        /// 富文本图像生成器
        case attributedTextImageGenerator
        /// Aztec码生成器
        case aztecCodeGenerator
        /// 条形码生成器
        case barcodeGenerator
        /// 条形滑动过渡
        case barsSwipeTransition
        /// 双三次缩放变换
        case bicubicScaleTransform
        /// 使用Alpha遮罩混合
        case blendWithAlphaMask
        /// 使用蓝色遮罩混合
        case blendWithBlueMask
        /// 使用遮罩混合
        case blendWithMask
        /// 使用红色遮罩混合
        case blendWithRedMask
        /// 泛光
        case bloom
        /// 柔化模糊
        case bokehBlur
        /// 盒式模糊
        case boxBlur
        /// 凸起畸变
        case bumpDistortion
        /// 线性凸起畸变
        case bumpDistortionLinear
        /// 相机校正镜头矫正
        case cameraCalibrationLensCorrection
        /// 棋盘图生成器
        case checkerboardGenerator
        /// 圆形飞溅畸变
        case circleSplashDistortion
        /// 圆形屏
        case circularScreen
        /// 圆形包裹
        case circularWrap
        /// 夹紧
        case clamp
        /// CMYK半色调
        case cMYKHalftone
        /// Code128条形码生成器
        case code128BarcodeGenerator
        /// 颜色绝对差异
        case colorAbsoluteDifference
        /// 颜色混合模式
        case colorBlendMode
        /// 颜色加深模式
        case colorBurnBlendMode
        /// 颜色夹紧
        case colorClamp
        /// 颜色控制
        case colorControls
        /// 颜色交叉多项式
        case colorCrossPolynomial
        /// 颜色立方体
        case colorCube
        /// 与遮罩混合的颜色立方体
        case colorCubesMixedWithMask
        /// 具有颜色空间的颜色立方体
        case colorCubeWithColorSpace
        /// 颜色曲线
        case colorCurves
        /// 颜色减淡模式
        case colorDodgeBlendMode
        /// 颜色反转
        case colorInvert
        /// 颜色地图
        case colorMap
        /// 颜色矩阵
        case colorMatrix
        /// 颜色单色
        case colorMonochrome
        /// 颜色多项式
        case colorPolynomial
        /// 颜色分色
        case colorPosterize
        /// 颜色阈值
        case colorThreshold
        /// Otsu颜色阈值
        case colorThresholdOtsu
        /// 列均值
        case columnAverage
        /// 漫画效果
        case comicEffect
        /// 固定颜色生成器
        case constantColorGenerator
        /// 转换Lab到RGB
        case convertLabToRGB
        /// 转换RGB到Lab
        case convertRGBtoLab
        /// 3x3卷积
        case convolution3X3
        /// 5x5卷积
        case convolution5X5
        /// 7x7卷积
        case convolution7X7
        /// 9x水平卷积
        case convolution9Horizontal
        /// 9x垂直卷积
        case convolution9Vertical
        /// 3x3 RGB卷积
        case convolutionRGB3X3
        /// 5x5 RGB卷积
        case convolutionRGB5X5
        /// 7x7 RGB卷积
        case convolutionRGB7X7
        /// 9x水平RGB卷积
        case convolutionRGB9Horizontal
        /// 9x垂直RGB卷积
        case convolutionRGB9Vertical
        /// 复印机过渡效果
        case copyMachineTransition
        /// Core ML模型过滤器
        case coreMLModelFilter
        /// 裁剪
        case crop
        /// 晶化
        case crystallize
        /// 变暗混合模式
        case darkenBlendMode
        /// 深度模糊效果
        case depthBlurEffect
        /// 景深
        case depthOfField
        /// 深度到视差
        case depthToDisparity
        /// 差别混合模式
        case differenceBlendMode
        /// 圆盘模糊
        case discBlur
        /// 崩解过渡效果
        case disintegrateWithMaskTransition
        /// 视差到深度
        case disparityToDepth
        /// 位移扭曲
        case displacementDistortion
        /// 溶解过渡效果
        case dissolveTransition
        /// 抖动
        case dither
        /// 除法混合模式
        case divideBlendMode
        /// 文档增强
        case documentEnhancer
        /// 点彩效果
        case dotScreen
        /// 德罗斯特效果
        case droste
        /// 边缘保护上采样滤镜
        case edgePreserveUpsampleFilter
        /// 边缘
        case edges
        /// 运动边缘
        case edgeWork
        /// 八重反射平铺
        case eightfoldReflectedTile
        /// 排除混合模式
        case exclusionBlendMode
        /// 曝光调整
        case exposureAdjust
        /// 伪彩色
        case falseColor
        /// 闪光过渡效果
        case flashTransition
        /// 四重反射平铺
        case fourfoldReflectedTile
        /// 四重旋转平铺
        case fourfoldRotatedTile
        /// 四重平移平铺
        case fourfoldTranslatedTile
        /// Gabor梯度
        case gaborGradients
        /// 伽马调整
        case gammaAdjust
        /// 高斯模糊
        case gaussianBlur
        /// 高斯梯度
        case gaussianGradient
        /// 玻璃失真
        case glassDistortion
        /// 玻璃菱形
        case glassLozenge
        /// 滑行反射平铺
        case glideReflectedTile
        /// 朦胧
        case gloom
        /// 引导滤波器
        case guidedFilter
        /// 强光混合模式
        case hardLightBlendMode
        /// 交织屏幕
        case hatchedScreen
        /// 从遮罩生成高度场
        case heightFieldFromMask
        /// 六角像素化
        case hexagonalPixellate
        /// 高光阴影调整
        case highlightShadowAdjust
        /// 直方图显示过滤器
        case histogramDisplayFilter
        /// 孔洞扭曲
        case holeDistortion
        /// 色调调整
        case hueAdjust
        /// 色调混合模式
        case hueBlendMode
        /// 色调饱和度值渐变
        case hueSaturationValueGradient
        /// 倾斜校正（组合）
        case keystoneCorrectionCombined
        /// 倾斜校正（水平）
        case keystoneCorrectionHorizontal
        /// 倾斜校正（垂直）
        case keystoneCorrectionVertical
        /// kMeans聚类
        case kMeans
        /// labDeltaE
        case labDeltaE
        /// lanczos缩放变换
        case lanczosScaleTransform
        /// lenticularHalo生成器
        case lenticularHaloGenerator
        /// lighten混合模式
        case lightenBlendMode
        /// lightTunnel
        case lightTunnel
        /// linearBurn混合模式
        case linearBurnBlendMode
        /// linearDodge混合模式
        case linearDodgeBlendMode
        /// 线性渐变
        case linearGradient
        /// linearLight混合模式
        case linearLightBlendMode
        /// 线性到SRGBTone曲线
        case linearToSRGBToneCurve
        /// lineOverlay
        case lineOverlay
        /// lineScreen
        case lineScreen
        /// luminosity混合模式
        case luminosityBlendMode
        /// maskedVariable模糊
        case maskedVariableBlur
        /// mask转alpha
        case maskToAlpha
        /// 最大分量
        case maximumComponent
        /// 最大合成
        case maximumCompositing
        /// 中值滤波
        case medianFilter
        /// 网格生成器
        case meshGenerator
        /// 最小分量
        case minimumComponent
        /// 最小合成
        case minimumCompositing
        /// 混合
        case mix
        /// mod过渡
        case modTransition
        /// 形态学梯度
        case morphologyGradient
        /// 形态学最大值
        case morphologyMaximum
        /// 形态学最小值
        case morphologyMinimum
        /// 形态学矩形最大值
        case morphologyRectangleMaximum
        /// 形态学矩形最小值
        case morphologyRectangleMinimum
        /// 运动模糊
        case motionBlur
        /// multiply混合模式
        case multiplyBlendMode
        /// multiply合成
        case multiplyCompositing
        /// 九部分拉伸
        case ninePartStretched
        /// 九部分平铺
        case ninePartTiled
        /// 降噪
        case noiseReduction
        /// opTile
        case opTile
        /// 叠加混合模式
        case overlayBlendMode
        /// 翻页过渡效果
        case pageCurlTransition
        /// 带阴影的翻页过渡效果
        case pageCurlWithShadowTransition
        /// 调色板中心点
        case paletteCentroid
        /// 调色板化
        case palettize
        /// 平行四边形平铺
        case parallelogramTile
        /// PDF417条形码生成器
        case pDF417BarcodeGenerator
        /// 人物分割
        case personSegmentation
        /// 透视校正
        case perspectiveCorrection
        /// 透视旋转
        case perspectiveRotate
        /// 透视平铺
        case perspectiveTile
        /// 透视变换
        case perspectiveTransform
        /// 带范围的透视变换
        case perspectiveTransformWithExtent
        /// 单色印刷效果
        case photoEffectChrome
        /// 淡化效果
        case photoEffectFade
        /// 瞬间效果
        case photoEffectInstant
        /// 单色效果
        case photoEffectMono
        /// 黑白效果
        case photoEffectNoir
        /// 冲印效果
        case photoEffectProcess
        /// 色调效果
        case photoEffectTonal
        /// 色彩迁移效果
        case photoEffectTransfer
        /// 捏合扭曲
        case pinchDistortion
        /// pinLight混合模式
        case pinLightBlendMode
        /// 像素化
        case pixellate
        /// 点状化
        case pointillize
        /// 二维码生成器
        case qrCodeGenerator
        /// 放射渐变
        case radialGradient
        /// 随机数生成器
        case randomGenerator
        /// 水波过渡效果
        case rippleTransition
        /// 圆角矩形生成器
        case roundedRectangleGenerator
        /// 行平均
        case rowAverage
        /// 显著性图滤镜
        case saliencyMapFilter
        /// 最近采样
        case sampleNearest
        /// 饱和度混合模式
        case saturationBlendMode
        /// 屏幕混合模式
        case screenBlendMode
        /// 乌墨色调
        case sepiaTone
        /// 阴影材质
        case shadedMaterial
        /// 锐化亮度
        case sharpenLuminance
        /// 六重反射平铺
        case sixfoldReflectedTile
        /// 六重旋转平铺
        case sixfoldRotatedTile
        /// 平滑线性渐变
        case smoothLinearGradient
        /// 柔光混合模式
        case softLightBlendMode
        /// 源在上合成
        case sourceAtopCompositing
        /// 源在内合成
        case sourceInCompositing
        /// 源在外合成
        case sourceOutCompositing
        /// 源在上方合成
        case sourceOverCompositing
        /// 斑点颜色
        case spotColor
        /// 聚光灯
        case spotLight
        /// sRGB曲线转线性
        case sRGBToneCurveToLinear
        /// 星光发生器
        case starShineGenerator
        /// 矫正滤镜
        case straightenFilter
        /// 拉伸裁剪
        case stretchCrop
        /// 条纹生成器
        case stripesGenerator
        /// 减去混合模式
        case subtractBlendMode
        /// 阳光发生器
        case sunbeamsGenerator
        /// 滑动过渡效果
        case swipeTransition
        /// 色温和色调
        case temperatureAndTint
        /// 文字图像生成器
        case textImageGenerator
        /// 热感图像
        case thermal
        /// 色调曲线
        case toneCurve
        /// 环面镜头畸变
        case torusLensDistortion
        /// 三角形万花筒
        case triangleKaleidoscope
        /// 三角形平铺
        case triangleTile
        /// 十二重反射平铺
        case twelvefoldReflectedTile
        /// 缠绕畸变
        case twirlDistortion
        /// 不锐化遮罩
        case unsharpMask
        /// 色彩饱和度
        case vibrance
        /// 暗角
        case vignette
        /// 暗角效果
        case vignetteEffect
        /// 鲜艳光混合模式
        case vividLightBlendMode
        /// 漩涡畸变
        case vortexDistortion
        /// 白点调整
        case whitePointAdjust
        /// X光
        case xRay
        /// 缩放模糊
        case zoomBlur
    }
}

// MARK: - AxcCIFilterCategory.BuiltIn + _AxcCIFilterNameProtocol

extension AxcCIFilterCategory.BuiltIn: _AxcCIFilterNameProtocol { }
